export enum ErrorMessages {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_FOUND = 'NOT_FOUND',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
